def imageName = 'lyteabovenyte/movies-loader'

node('worker'){
    stage('Checkout'){
        git branch 'develop',
        credentialsId: 'github-ssh',
        url: 'git@github.com:lyteabovenyte/movies-loader.git'
    }
    stage('Unit Tests'){
        def ImageTest = docker.build("${imageName}-test", "-f Dockerfile.test .")
        imageTest.inside{
            sh 'python test-main.py'
        }
    }
}