def imageName = 'lyteabovenyte/movies-loader'
def registry = 'https://registry.amir.com'
def commitID() {
    sh 'git rev-parse HEAD > .git/commitID'
    def commitID = readFile('.git/commitID').trim()
    sh 'rm .git/commitID'
    commitID
}

node('worker'){
    stage('Checkout'){
        git branch 'develop',
        credentialsId: 'github-ssh',
        url: 'git@github.com:lyteabovenyte/movies-loader.git'
    }
    stage('Unit Tests'){
        def ImageTest = docker.build("${imageName}-test", "-f Dockerfile.test .")
        sh "docker run --rm -v $PWD/reports:/app/reports ${imageName}-test"
        junit "$PWD/reports/*.xml"
    }
    stage('Build') {
        docker.build(imageName)
    }
    stage('Push') {
        sh "aws ecr get-login-password --region ${REGION} |
        docker login --username AWS --password-stdin ${registry}/${imageName}"

        docker.withRegistry(registry, 'registry') {
            docker.image(imageName).push(commitID())

        if (env.BRANCH_NAME = 'develop') {
            docker.image(imageName).push('develop')
        }
        }
    }
}