def imageName = 'lyteabovenyte/movies-loader'

node('worker'){
    stage('Checkout'){
        git branch 'develop',
        credentialsId: 'github-ssh',
        url: 'git@github.com:lyteabovenyte/movies-loader.git'
    }
    stage('Unit Tests'){
        def ImageTest = docker.build("${imageName}-test", "-f Dockerfile.test .")
        sh "docker run --rm -v $PWD/reports:/app/reports ${imageName}-test"
        junit "$PWD/reports/*.xml"
    }
    stage('Build') {
        docker.build(imageName)
    }
}