def imageName = 'lyteabovenyte/moveis-parser'

node('worker'){
    stage('Checkout'){
        checkout scm
    }
    
    def imageTest = docker.build("${imageName}-test", "-f Dockerfile.test .")

    stage('Pre-integration Tests'){
        parallel(
            'Quality Tests': {
                imageTest.inside{
                    sh 'golint'
                }
            },
            'Unit Test': {
                imageTest.inside{
                    sh 'go test'
                    sh 'go test -coverprofile=cover/cover.cov'
                    sh 'go tool cover -html=cover/coverage.cov -o coverage.html'
                }
            }
            'Security Test': {
                imageTest.inside(-u root:root){
                    sh 'nancy Gopkg.lock'
                }
            }
        )
    }
}