def imageName = 'lyteabovenyte/moveis-parser'

node('worker'){
    stage('Checkout'){
        checkout scm
    }
    
    def imageTest = docker.build("${imageName}-test", "-f Dockerfile.test .")

    stage('Quality Tests'){
        imageTest.inside{
            sh 'golint'
        }
    }

    stage('Unit Tests'){
        imageTest.inside{
            sh 'go test'
            sh 'go test -coverprofile=cover/cover.cov'
            sh 'go tool cover -html=cover/coverage.cov -o coverage.html'
        }
    }
}